# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: lazyopenconnect

before:
  hooks:
    - go mod tidy

builds:
  - id: lazyopenconnect
    binary: lazyopenconnect
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Other"
      order: 999

release:
  github:
    owner: Nybkox
    name: lazyopenconnect
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## Installation

    ### Quick Install (macOS/Linux)
    ```bash
    curl -fsSL https://raw.githubusercontent.com/Nybkox/lazyopenconnect/main/install.sh | bash
    ```

    ### Manual Download
    Download the appropriate archive for your platform below.

brews:
  - repository:
      owner: Nybkox
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/Nybkox/lazyopenconnect"
    description: "TUI for managing OpenConnect VPN connections"
    license: "MIT"
    install: |
      bin.install "lazyopenconnect"
    test: |
      system "#{bin}/lazyopenconnect", "--version"
